# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class Usb(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, id=None, name=None, status=None):  # noqa: E501
        """Usb - a model defined in OpenAPI

        :param id: The id of this Usb.  # noqa: E501
        :type id: int
        :param name: The name of this Usb.  # noqa: E501
        :type name: str
        :param status: The status of this Usb.  # noqa: E501
        :type status: str
        """
        self.openapi_types = {
            'id': int,
            'name': str,
            'status': str
        }

        self.attribute_map = {
            'id': 'id',
            'name': 'name',
            'status': 'status'
        }

        self._id = id
        self._name = name
        self._status = status

    @classmethod
    def from_dict(cls, dikt) -> 'Usb':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Usb of this Usb.  # noqa: E501
        :rtype: Usb
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self):
        """Gets the id of this Usb.


        :return: The id of this Usb.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Usb.


        :param id: The id of this Usb.
        :type id: int
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this Usb.


        :return: The name of this Usb.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this Usb.


        :param name: The name of this Usb.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def status(self):
        """Gets the status of this Usb.

        usb status  # noqa: E501

        :return: The status of this Usb.
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this Usb.

        usb status  # noqa: E501

        :param status: The status of this Usb.
        :type status: str
        """
        allowed_values = ["low", "high"]  # noqa: E501
        if status not in allowed_values:
            raise ValueError(
                "Invalid value for `status` ({0}), must be one of {1}"
                .format(status, allowed_values)
            )

        self._status = status
