#user  nobody;
worker_processes  1;

#error_log  logs/error.log;
#error_log  logs/error.log  notice;
#error_log  logs/error.log  info;

#pid        logs/nginx.pid;


events {
    worker_connections  10;
}

http {
    include       mime.types;
    default_type  application/octet-stream;

    sendfile        on;
    
    keepalive_timeout  65;

    map $http_upgrade $connection_upgrade {
        default upgrade;
        "" close;
    }

    upstream smarthub {
        server 127.0.0.1:8080; # smarthub REST API
    }

    upstream smarthub-websocket{
    	server 127.0.0.1:9001; # smarthub websocket
    }

    upstream smarthub-serial{
    	server 127.0.0.1:9002; # smarthub serial
    }

    upstream smarthub-streaming{
    	server 127.0.0.1:9003; # smarthub serial
    }

    include nginx_http.conf;

}
