location /v2/ {
    proxy_pass http://smarthub/v2/;
}


location /smarthub-websocket {
    proxy_pass http://smarthub-websocket;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $connection_upgrade;
}

location /smarthub-serial {
    proxy_pass http://smarthub-serial;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $connection_upgrade;
}

location /smarthub-streaming{
    proxy_pass http://smarthub-streaming
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $connection_upgrade;
}


